-- A lexical scanner generated by aflex
with text_io; use text_io;
with small_dfa; use small_dfa; 
with small_io; use small_io; 
--# line 1 "small.l"
-- Automatically generated file
-- from AdaGOOP2005 (by Martin C. Carlisle)
-- If modified, be careful about losing work.
--# line 12 "small.l"

package small is
   Invalid_Character : exception; -- only can handle ASCII 0..127
   type Token is (
      End_Of_Input,
      Error,
      STRING_token,
      RPAREN_token,
      LPAREN_token,
      COMMA_token,
      TIMES_token,
      MINUS_token,
      PLUS_token,
      DONE_token,
      ID_token,
      NUMBER_token,
      TURTLES_token,
      TO_token,
      SET_token,
      RBRACK_token,
      RANDOMFLT_token,
      RANDOM_token,
      PYCOR_token,
      PXCOR_token,
      PCOLOR_token,
      LBRACK_token,
      OUTPUTPRINT_token,
      OR_token,
      IF_token,
      HEADING_token,
      GLOBALS_token,
      FORWARD_token,
      END_token,
      CLEARALL_token,
      ASK_token,
      AND_token,
      Dummy_Token);

   procedure Reset(Filename : in String);
   function Get_Token return Token;
   function Get_Token_String return String;
   function Get_Current_Line return Natural;
   function Get_Current_Column return Natural;
   procedure Close_Files;
end small;
