-- A lexical scanner generated by aflex
with text_io; use text_io;
with test_dfa; use test_dfa; 
with test_io; use test_io; 
--# line 1 "test.l"
-- Automatically generated file
-- from AdaGOOP2005 (by Martin C. Carlisle)
-- If modified, be careful about losing work.
--# line 12 "test.l"

package test is
   Invalid_Character : exception; -- only can handle ASCII 0..127
   type Token is (
      End_Of_Input,
      Error,
      WRITE_token,
      WHILE_token,
      TYPE_token,
      THEN_token,
      RECORD_token,
      REAL_token,
      READ_token,
      PROCEDURE_token,
      OR_token,
      OPEN_token,
      OF_token,
      NOT_token,
      INTEGER_token,
      IF_token,
      FUNCTION_token,
      END_token,
      ELSE_token,
      DO_token,
      CLOSE_token,
      BOOLEAN_token,
      BEGIN_token,
      ARRAY_token,
      AND_token,
      Dummy_Token);

   procedure Reset(Filename : in String);
   function Get_Token return Token;
   function Get_Token_String return String;
   function Get_Current_Line return Natural;
   function Get_Current_Column return Natural;
   procedure Close_Files;
end test;
